title: QA in Practice
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/qa-in-practice"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Thiago Ferreira
author-img: thiago-ferreira.png # add your photo
about-author: I am a quality assurance engineer and conference speaker. Trying to make quality a habit.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: tferreiramachado
social-linkedin: thiago-ferreira-03735066
social-email: tferreiramachado@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
